# Generated by Django 3.2.4 on 2021-07-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('studyGroupId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('groupName', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=5000)),
            ],
            options={
                'db_table': 'studygroups',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=40, unique=True)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('role', models.IntegerField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='./static/')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='StudyGroupPost',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('postTitle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=5000)),
                ('postDateTime', models.DateTimeField(auto_now=True)),
                ('studyGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.studygroup')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.user')),
            ],
            options={
                'db_table': 'studygroupposts',
            },
        ),
        migrations.CreateModel(
            name='StudyGroupComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=5000)),
                ('commentDateTime', models.DateTimeField(auto_now=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.studygrouppost')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.user')),
            ],
            options={
                'db_table': 'studygroupcomments',
            },
        ),
        migrations.AddField(
            model_name='studygroup',
            name='ownerId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.user'),
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studyGroupId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.studygroup')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.user')),
            ],
            options={
                'db_table': 'members',
            },
        ),
        migrations.CreateModel(
            name='MainPost',
            fields=[
                ('postId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('postTitle', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=5000)),
                ('postDateTime', models.DateTimeField(auto_now=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.user')),
            ],
            options={
                'db_table': 'mainposts',
            },
        ),
        migrations.CreateModel(
            name='MainComment',
            fields=[
                ('commentId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('comment', models.CharField(max_length=5000)),
                ('commentDateTime', models.DateTimeField(auto_now=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.mainpost')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.user')),
            ],
            options={
                'db_table': 'maincomments',
            },
        ),
    ]
