# Generated by Django 3.2.4 on 2021-07-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('general', 'general'), ('educator', 'educator'), ('admin', 'admin')], default='general', max_length=10),
        ),
    ]
