# Generated by Django 3.2.4 on 2021-07-15 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0003_auto_20210713_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatRoom',
            fields=[
                ('chatRoomId', models.AutoField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'db_table': 'chatrooms',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=45)),
                ('telephone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=45)),
                ('message', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
        migrations.RenameModel(
            old_name='Member',
            new_name='StudyGroupMember',
        ),
        migrations.AddField(
            model_name='studygroup',
            name='groupType',
            field=models.CharField(choices=[('general', 'general'), ('educator', 'educator')], default='general', max_length=10),
        ),
        migrations.AddField(
            model_name='studygroup',
            name='memberCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='studygroupmember',
            table='studygroupmembers',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messageId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('message', models.CharField(max_length=5000)),
                ('messageDateTime', models.DateTimeField(auto_now=True)),
                ('chatRoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.chatroom')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'messages',
            },
        ),
        migrations.CreateModel(
            name='ChatMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatRoomId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='study_app.chatroom')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chatmembers',
            },
        ),
    ]
