# Generated by Django 3.2.4 on 2021-07-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_app', '0006_auto_20210728_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studygroup',
            name='groupName',
            field=models.CharField(max_length=100),
        ),
    ]
